export const collection_list = [
  // "bongbears",
  // "bond-bears",
  // "boo-bears",
  // "the-baby-bears",
  // "the-band-bears",
  // "berachain-bit-bears",
  // "honey-comb-2",
  // "honeyjar",
  "honeyjar-gen-2",
  // "honeyjar-gen-3",
  // "honeyjar-gen-4",
  "the-fable-beras",
  // "hookedonbera",
  "fable-chronicles-1",
  // "beramonium-chronicles-genesis",
  // "beratone-founders-sailcloth",
  "berautistics-1",
  "yeetard-nfts",
  "cubhub",
  // "thc-nft-2",
  "tour-de-berance",
  "cooked-cxnts",
  "hungrybera",
  "booga-beras-5",
  "honeygenesis-arbitrum",
  "smilee-beras",
  "happeeberas",
  "big-fat-beras-beraborrow",
  "beraboyz-4",
  "onikuma-genesis-nft-2",
  "bera-punks",
  "beradelic",
  "pluggy-tings",
  "arkto-genesis-3",
  "theproofofjunkie",
  "petragunn",
  "oasisopus-class4",
  "blue-beras-8",
  "baka-bears",
  "bera-cards-6",
  "narrazai-1",
  "kumamon-1",
  "bruuvvprint-memeswap",
  "beracpol2-3",
  "beracpol-2",
  "berac",
  "beracid-1",
  // "bera-horses",
  // "shroomieznfts",
  "dream-masks",
  "printing-burrberas-5",
  "the-bearet-yellens-1",
  "beary-benslers",
  "npc-beras-4",
  "chrono-wizard-bear",
  "bera-packs",
  "beranauts-1",
  // "an-oath-to-er",
];
